baseURL = 'https://portfolio.iemafzalhassan.in/'
languageCode = 'en-us'
title = 'iemafzalhassan'
theme = 'PaperMod'

# Enable features
enableGitInfo = false
enableEmoji = true
enableRobotsTXT = true
enableFingerprinting = true
enableInlineShortcodes = true
enableMissingTranslationPlaceholders = false

# Main sections for recent articles
mainSections = ["blogs", "projects"]

# Build settings
publishDir = 'public'

# Menu configuration
[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    identifier = 'blogs'
    name = 'Blog'
    url = '/blogs/'
    weight = 20
  [[menu.main]]
    identifier = 'projects'
    name = 'Projects'
    url = '/projects/'
    weight = 30
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 40

# PaperMod theme parameters
[params]
  env = 'production'
  title = 'Afzal Hassan - DevOps Engineer'
  description = 'DevOps Engineer | AWS, Azure, GCP, Kubernetes, Terraform | Building scalable, automated, and secure infrastructure at scale'
  
  # Author information
  [params.author]
    name = "Afzal Hassan"
    image = "/img/profile.png"
    email = "iemafzalhassan@gmail.com"
    
  # Footer configuration
  [params.footer]
    enable = true
    showMenu = true
    showCopyright = true
    showThemeAttribution = false
    showScrollToTop = true
    hideFooter = false
    text = "Building the future, one deployment at a time."

# Enhanced taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
  author = "authors"

# Enhanced markup settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      xhtml = false
  [markup.highlight]
    style = "dracula"
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    tabWidth = 4
    trimPrefix = ""
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    hl_inline = false
    lineNoStart = 1
    lineNosTable = false