baseURL = 'https://iemafzalhassan.me/portfolio-pages/'
languageCode = 'en-us'
title = 'iemafzalhassan'
theme = 'blowfish'

# Enable features
enableGitInfo = false
enableEmoji = true
enableRobotsTXT = true
enableSearch = true
enableFingerprinting = false

# Build settings
publishDir = 'public'

# Menu configuration
[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    identifier = 'blogs'
    name = 'Posts'
    url = '/blogs/'
    weight = 20
  [[menu.main]]
    identifier = 'projects'
    name = 'Projects'
    url = '/projects/'
    weight = 30
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 40

# Blowfish theme parameters
[params]
  description = "DevOps Engineer & Cloud Enthusiast | AWS, Azure, Kubernetes, Terraform"
  colorScheme = "noir"

  [params.author]
    name = "Afzal Hassan"
    bio = "DevOps Engineer & Cloud Enthusiast"
    links = [
      { name = "GitHub", icon = "github", url = "https://github.com/iemafzalhassan" },
      { name = "LinkedIn", icon = "linkedin", url = "https://www.linkedin.com/in/iemafzalhassan/" },
      { name = "Twitter", icon = "twitter", url = "https://x.com/iemafzalhassan" }
    ]

  [params.header]
    layout = "fixed"
    desktopMode = "fixed"
    mobileMode = "auto"

  [params.footer]
    enable = true
    showMenu = true
    showCopyright = true
    showThemeAttribution = false
    showAppearanceSwitcher = true

  [params.search]
    enable = true
    type = "fuse"
    fuseOpts = { keys = ["title", "permalink", "summary", "content"] }

  [params.homepage]
    layout = "page"
    showRecent = true
    recentLimit = 3
    showFullTextinRSS = true
