baseURL = 'https://iemafzalhassan.me/portfolio-pages/'
languageCode = 'en-us'
title = 'Afzal Hassan - DevOps Engineer'
theme = 'blowfish'

# Enable features
enableGitInfo = false
enableEmoji = true
enableRobotsTXT = true
enableSearch = true
enableFingerprinting = false

# Build settings
publishDir = 'public'

# Menu configuration
[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    identifier = 'blogs'
    name = 'Posts'
    url = '/blogs/'
    weight = 20
  [[menu.main]]
    identifier = 'projects'
    name = 'Projects'
    url = '/projects/'
    weight = 30
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 40

# Blowfish theme parameters
[params]
  # Site description
  description = "DevOps Engineer & Cloud Enthusiast | AWS, Azure, Kubernetes, Terraform"
  
  # Color scheme - Noir theme
  colorScheme = "noir"
  
  # Author information
  [params.author]
    name = "Afzal Hassan"
    image = "/img/profile.png"
    bio = "DevOps Engineer & Cloud Enthusiast"
    links = [
      { name = "GitHub", url = "https://github.com/iemafzalhassan" },
      { name = "LinkedIn", url = "https://www.linkedin.com/in/iemafzalhassan/" },
      { name = "Twitter", url = "https://x.com/iemafzalhassan" }
    ]
  
  # Header configuration
  [params.header]
    layout = "fixed"
    desktopMode = "fixed"
    mobileMode = "auto"
  
  # Footer configuration
  [params.footer]
    enable = true
    showMenu = true
    showCopyright = true
    showThemeAttribution = true
    showAppearanceSwitcher = true
  
  # Search configuration
  [params.search]
    enable = true
    type = "fuse"
    fuseOpts = { keys = ["title", "permalink", "summary", "content"] }
  
  # Social icons
  [params.socialIcons]
    github = "https://github.com/iemafzalhassan"
    linkedin = "https://www.linkedin.com/in/iemafzalhassan/"
    twitter = "https://x.com/iemafzalhassan"
  
  # Home page configuration
  [params.homepage]
    layout = "page"
    showRecent = true
    recentLimit = 6
    showFullTextinRSS = true
